version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 4.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = true
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
universal_ores = true
fastitemframes = true
nightlights = true
supplementaries = true
enchanted-vertical-slabs = true
brickfurnace = true
natures_spirit = true
clutter = true
items_displayed = true
adorablehamsterpets = true
easymagic = true
ribbits = true
yungscavebiomes = true
enc_vanilla = true
chimes = true
ironchest = true
friendsandfoes = true
easyanvils = true
glassential = true
visualworkbench = true
ecologics = true
copperhopper = true
minecraft = true
visualoverhaul = true
diagonalwalls = true
lootr = true
comforts = true
elevatorid = true
yigd = true
more_useful_copper = true
playerplates = true
usefulslime = true
amendments = true
creeperoverhaul = true
monolib = true
diagonalwindows = true
rocks = true
lolmct = true
snowrealmagic = true
diagonalfences = true
crittersandcompanions = true
charm = true
