version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = false
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 4.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
universal_ores = true
fastitemframes = true
nightlights = true
supplementaries = true
enchanted-vertical-slabs = true
clutter = true
adorablehamsterpets = true
easymagic = true
yungscavebiomes = true
enc_vanilla = true
items_displayed = true
natures_spirit = true
easyanvils = true
glassential = true
visualworkbench = true
ecologics = true
minecraft = true
visualoverhaul = true
diagonalwalls = true
lootr = true
comforts = true
yigd = true
elevatorid = true
playerplates = true
amendments = true
creeperoverhaul = true
usefulslime = true
diagonalwindows = true
rocks = true
lolmct = true
snowrealmagic = true
diagonalfences = true
crittersandcompanions = true
charm = true
